services:
  test1:
    build:
      context: ./services/example1/
      dockerfile: DOCKERFILE
    image: ${registry1}test1:latest
    platform: "linux/amd64"
    ports:
      - "8080:80"
    restart: unless-stopped

  test2:
    build:
      context: ./services/example2/
      dockerfile: Dockerfile
    image: ${registry2}test2:latest
    platform: "linux/amd64"
    ports:
      - "8081:8080"
    environment:
      - EXPOSE_SERVEO="false"
    restart: unless-stopped

  langgraph_deterministic_graph_example:
    build:
      context: ./services/langgraph_deterministic_graph_example/
      dockerfile: Dockerfile
    image: ${regdomyn}langgraph-deterministic-graph-example:latest
    platform: "linux/amd64"
    restart: unless-stopped

  langgraph_agent_example:
    build:
      context: ./services/langgraph_agent_example/
      dockerfile: Dockerfile
    image: ${regdomyn}langgraph-agent-example:latest
    platform: "linux/amd64"
    restart: unless-stopped

  guardrail-custom-ui-example:
    build:
      context: ./services/custom_ui_guardrail/
      dockerfile: Dockerfile
    image: ${regdomyn}guardrail-custom-ui-example:latest
    restart: unless-stopped
  
  minimal-guardrail-example:
    build:
      context: ./services/minimal_guardrail/
      dockerfile: Dockerfile
    image: ${regdomyn}minimal-guardrail-example:latest
    restart: unless-stopped
