dns:
  postfix: "qa.crystal.io"
kubernetes: 
  context: crystal-qa-azure-us
helm:
  chart: ./kubernetes/charts/services
  namespace: qa-tools
  # values_files: 
  #   - ./kubernetes/values.test.yaml
registries: 
  - eu.gcr.io/igenius-registry
containers:
  platform: "linux/amd64"
services:
  path: ./services/
