version: '3'

dotenv:
  - .env

vars:
  helm_release_name: "services"
  namespace: "test"

tasks:

  default:
    internal: true
    cmd: task --list

  build:
    desc: Build the Docker image for the service.
    cmd: docker compose build

  local:deploy:
    desc: Deploy the service locally using Docker Compose.
    cmd: docker compose up -d

  local:remove:
    desc: Remove the local deployment of the service.
    cmd: docker compose down

  local:test:
    desc: Test the local deployment of the service using curl.
    cmds:
      - task: test
        vars:
          ip: "127.0.0.1"
          host: "localhost"
  
  test:
    internal: true
    desc: Curl the service at a specified IP using a specified hostname.
    requires:
      vars:
        - ip
        - host
    cmd: curl -v --resolve "{{.host}}:8080:{{.ip}}" "http://{{.host}}:8080"

  cluster:deploy:
    desc: Deploy the service to a Kubernetes cluster using Helm.
    vars:
      namespace: "{{.namespace}}"
      helm_release_name: "{{.helm_release_name}}"
    cmd: helm upgrade --install {{.helm_release_name}} ./kubernetes/helm/services --values kubernetes/helm/values.test.yaml --namespace {{.namespace}} --create-namespace

  cluster:remove:
    desc: Remove the service from the Kubernetes cluster.
    vars:
      namespace: "{{.namespace}}"
      helm_release_name: "{{.helm_release_name}}"
    cmd: helm uninstall {{.helm_release_name}} --namespace {{.namespace}}
