services:
  - name: custom-ui-guardrail
    image:
      registry: "eu.gcr.io/igenius-registry"
      repository: custom_ui_guardrail
      tag: "latest"
      pullPolicy: Always
    imagePullSecrets:
      - name: vault-image-pull-secrets
    env:
      - name: "MODEL_NAME"
        value: "Qwen/Qwen3-32B"
      - name: "URL"
        value: "https://gateway-dev.llm.crystal.ai/v1/chat/completions"
      - name: "API_KEY"
        valueFrom:
          secretKeyRef:
            name: "credential-test-secret"
            key: "VLLM_API_KEY"
    ingress:
      enabled: true
      host: "blueprint"
      ingressClass: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      portName: http
      exposeName: "http"
      targetPort: 8080
      tls:
        enabled: true
        secretName: "tls-blueprint"
