forceRestart: true
services:
  - name: example1
    image:
      registry: "eu.gcr.io/igenius-registry"
      repository: example1
      tag: "latest"
      pullPolicy: Always
    imagePullSecrets:
      - name: image-pull-secrets
    # expose:
    #   - name: external1
    #     type: LoadBalancer
    #     ports:
    #       - port: 8080
    #         targetPort: 80
    #         name: http-lb
    #         protocol: TCP
    ingress:
      enabled: true
      host: "example1"
      ingressClass: nginx
      targetPort: 80
      exposeName: ""
      tls:
        enabled: true
        secretName: "tls-secret-example1"
