{{- range .Values.services }}
{{- if and .ingress .ingress.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" $ }}-{{ .name }}-ingress
  labels:
    {{- include "service.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  type: ClusterIP
  selector:
    {{- include "service.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .ingress.targetPort | default 80 }}
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.fullname" $ }}-{{ .name }}
  labels:
    {{- include "service.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
  annotations:
    kubernetes.io/ingress.class: {{ .ingress.ingressClass | default "nginx" }}
spec:
  {{- if and .ingress.tls .ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .ingress.host }}
      secretName: {{ .ingress.tls.secretName | default (printf "%s-%s-tls" (include "service.fullname" $) .name) }}
  {{- end }}
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "service.fullname" $ }}-{{ .name }}-ingress
                port:
                  name: http
{{- end }}
{{- end }}
