{{- range .Values.services }}
{{- $svc := . }}
{{- range .expose }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.exposeName" (dict "root" $ "component" $svc.name "expose" .name) }}
  labels:
    {{- include "service.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $svc.name }}
spec:
  type: {{ .type | default "LoadBalancer" }}
  ports:
    {{- range .ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "service.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $svc.name }}
{{- end }}
{{- end }}
