services:
  - name: example1
    image:
      registry: "reg1"
      repository: test1
      tag: "latest"
      pullPolicy: Never
    ingress:
      enabled: true
      host: "localhost"
      ingressClass: nginx
      portName: http
      tls:
        enabled: false
        secretName: "tls-secret"
    type: LoadBalancer
    ports:
      - port: 8080
        targetPort: 80
        name: http
        protocol: TCP
