services:
  - name: langgraph-deterministic-graph-example
    image:
      registry: "eu.gcr.io/igenius-registry"
      repository: langgraph-deterministic-graph-example
      tag: "latest"
      pullPolicy: Always
    imagePullSecrets:
      - name: vault-image-pull-secrets
    env:
      - name: PLATFORM_BASE_URL
        value: "analytics-az.crystal.io"
      - name:   SPACE_ID
        value: 9db0eaf1-b2c9-4afd-ac6e-f8185473a4ea
      - name: CHANNEL_ID
        value: 63a1ad4c0bfa79c3182bd1e5af38
      - name: DOMYN_API_KEY
        valueFrom:
          secretKeyRef:
            name: blueprint
            key: DOMYN_API_KEY
  - name: guardrail-custom-ui-example
    image:
      registry: "eu.gcr.io/igenius-registry"
      repository: guardrail-custom-ui-example
      tag: "demo2"
      pullPolicy: Always
    imagePullSecrets:
      - name: vault-image-pull-secrets
    ingress:
      enabled: true
      host: "blueprint.devopscluster.crystal.io"
      ingressClass: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      portName: http
      exposeName: "http"
      targetPort: 8080
      tls:
        enabled: true
        secretName: "tls-blueprint"