{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" $ }}-{{ .name }}
  labels:
    {{- include "service.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
  {{- if and .tls .tls.enabled }}
  annotations:
    service.beta.kubernetes.io/load-balancer-ssl-cert: {{ .tls.secretName | default (printf "%s-%s-tls" (include "service.fullname" $) .name) }}
  {{- end }}
spec:
  type: {{ .type | default "LoadBalancer" }}
  ports:
    {{- range .ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "service.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
{{- end }}
