{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" $ }}-{{ .name }}
  labels:
    {{- include "service.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
{{- end }}
